import { initialApiBase } from "../api/endpoints.js";

export const elements = {
  legalDisclaimer: document.querySelector("#legalDisclaimer"),
  acceptDisclaimer: document.querySelector("#acceptDisclaimer"),
  apiBase: document.querySelector("#apiBase"),
  apiStatus: document.querySelector("#apiStatus"),
  saveApiBase: document.querySelector("#saveApiBase"),
  mobileMenuToggle: document.querySelector("#mobileMenuToggle"),
  amount: document.querySelector("#amount"),
  risk: document.querySelector("#risk"),
  riskValue: document.querySelector("#riskValue"),
  horizon: document.querySelector("#horizon"),
  forecastHorizon: document.querySelector("#forecastHorizon"),
  windowSize: document.querySelector("#windowSize"),
  windowSizeInline: document.querySelector("#windowSizeInline"),
  refreshDashboard: document.querySelector("#refreshDashboard"),
  freshnessBar: document.querySelector("#freshnessBar"),
  freshnessStatus: document.querySelector("#freshnessStatus"),
  freshnessLatest: document.querySelector("#freshnessLatest"),
  freshnessSource: document.querySelector("#freshnessSource"),
  freshnessStale: document.querySelector("#freshnessStale"),
  learnModeToggle: document.querySelector("#learnModeToggle"),
  themeModeToggle: document.querySelector("#themeModeToggle"),
  marketAsOf: document.querySelector("#marketAsOf"),
  marketIndices: document.querySelector("#marketIndices"),
  marketIndexSelect: document.querySelector("#marketIndexSelect"),
  marketIndexDateRange: document.querySelector("#marketIndexDateRange"),
  marketIndexSummary: document.querySelector("#marketIndexSummary"),
  marketIndexChart: document.querySelector("#marketIndexChart"),
  marketIndexChartFallback: document.querySelector("#marketIndexChartFallback"),
  marketHighlights: document.querySelector("#marketHighlights"),
  marketLessonCards: document.querySelector("#marketLessonCards"),
  macroSnapshot: document.querySelector("#macroSnapshot"),
  marketTable: document.querySelector("#marketTable"),
  sentimentGaugeArc: document.querySelector("#sentimentGaugeArc"),
  sentimentScore: document.querySelector("#sentimentScore"),
  sentimentLabel: document.querySelector("#sentimentLabel"),
  sentimentReasons: document.querySelector("#sentimentReasons"),
  marketInsightList: document.querySelector("#marketInsightList"),
  topOpportunities: document.querySelector("#topOpportunities"),
  dataHealthCards: document.querySelector("#dataHealthCards"),
  tickerSelect: document.querySelector("#tickerSelect"),
  runTickerForecast: document.querySelector("#runTickerForecast"),
  forecastDateRange: document.querySelector("#forecastDateRange"),
  forecastChart: document.querySelector("#forecastChart"),
  chartFallback: document.querySelector("#chartFallback"),
  tickerMetricTitle: document.querySelector("#tickerMetricTitle"),
  tickerMetrics: document.querySelector("#tickerMetrics"),
  tickerDataBadges: document.querySelector("#tickerDataBadges"),
  forecastChange: document.querySelector("#forecastChange"),
  forecastLessonContent: document.querySelector("#forecastLessonContent"),
  scenarioHorizonLabel: document.querySelector("#scenarioHorizonLabel"),
  scenarioPathSummary: document.querySelector("#scenarioPathSummary"),
  tickerInsights: document.querySelector("#tickerInsights"),
  tickerProfile: document.querySelector("#tickerProfile"),
  tickerAboutTitle: document.querySelector("#tickerAboutTitle"),
  tickerNarrative: document.querySelector("#tickerNarrative"),
  simulationTickers: document.querySelector("#simulationTickers"),
  maxSinglePosition: document.querySelector("#maxSinglePosition"),
  maxCryptoWeight: document.querySelector("#maxCryptoWeight"),
  minCashWeight: document.querySelector("#minCashWeight"),
  preferStock: document.querySelector("#preferStock"),
  preferEtf: document.querySelector("#preferEtf"),
  preferCrypto: document.querySelector("#preferCrypto"),
  runSimulation: document.querySelector("#runSimulation"),
  simulationSummary: document.querySelector("#simulationSummary"),
  simulationWarnings: document.querySelector("#simulationWarnings"),
  portfolioClassroom: document.querySelector("#portfolioClassroom"),
  simulationClasses: document.querySelector("#simulationClasses"),
  simulationAssets: document.querySelector("#simulationAssets"),
  simulationTrades: document.querySelector("#simulationTrades"),
  benchmarkComparison: document.querySelector("#benchmarkComparison"),
  allocationWhy: document.querySelector("#allocationWhy"),
  runRlAllocation: document.querySelector("#runRlAllocation"),
  runBacktest: document.querySelector("#runBacktest"),
  rlSummary: document.querySelector("#rlSummary"),
  rlClasses: document.querySelector("#rlClasses"),
  backtestSummary: document.querySelector("#backtestSummary"),
  backtestWarnings: document.querySelector("#backtestWarnings"),
  healthBlock: document.querySelector("#healthBlock"),
  modelsBlock: document.querySelector("#modelsBlock"),
  refreshStatusBlock: document.querySelector("#refreshStatusBlock"),
  projectStats: document.querySelector("#projectStats"),
  projectHighlights: document.querySelector("#projectHighlights"),
  projectTransparency: document.querySelector("#projectTransparency"),
  glossaryList: document.querySelector("#glossaryList"),
  footerDataAsOf: document.querySelector("#footerDataAsOf"),
};

export const state = {
  apiBase: initialApiBase(),
  universe: null,
  health: null,
  models: null,
  refreshStatus: null,
  simulation: null,
  backtest: null,
  chart: null,
  chartRange: "6m",
  marketIndexChart: null,
  marketIndexRange: "1y",
  marketIndexSymbol: "SP500",
  marketIndexAsOf: null,
  marketIndexHistory: null,
  currentForecast: null,
  pendingForecastTicker: null,
  sentiment: null,
  classAllocationSegments: [],
  learnMode: localStorage.getItem("foresight-learn-mode") === "true",
  themeMode: localStorage.getItem("foresight-theme-mode") || "dark",
  controllers: {},
  loaded: {
    market: false,
    forecast: false,
    simulator: false,
    diagnostics: false,
  },
};

export const glossary = {
  bear: {
    title: "Bear scenario",
    definition: "A weaker outcome that estimates what could happen if price and volatility move against the asset.",
  },
  base: {
    title: "Base scenario",
    definition: "The central estimate. It is useful for comparison, but it is not a guaranteed target.",
  },
  bull: {
    title: "Bull scenario",
    definition: "A stronger outcome that estimates potential upside if conditions are favorable.",
  },
  volatility: {
    title: "Volatility",
    definition: "A measure of how much prices may swing. Higher volatility usually means wider scenario ranges.",
  },
  drawdown: {
    title: "Max drawdown",
    definition: "The largest historical fall from a previous high. It helps explain downside pain, not just average return.",
  },
  confidence: {
    title: "Confidence",
    definition: "A model-readiness score that falls when history is thin, volatility is high, or scenario bands are wide.",
  },
  sharpe: {
    title: "Sharpe ratio",
    definition: "A risk-adjusted return measure. Higher values mean more return per unit of volatility in the backtest.",
  },
  diversification: {
    title: "Diversification",
    definition: "Spreading exposure across assets so one holding does not dominate the portfolio outcome.",
  },
  cash: {
    title: "Cash buffer",
    definition: "A lower-risk sleeve the simulator can hold when downside risk or uncertainty is elevated.",
  },
  spread: {
    title: "Scenario spread",
    definition: "The distance between bear and bull outcomes. A wider spread means the model sees more uncertainty.",
  },
  freshness: {
    title: "Data freshness",
    definition: "The latest market date used by the model. Fresh data matters because forecasts start from recent prices.",
  },
};

export const literacy = Object.fromEntries(
  Object.entries(glossary).map(([key, value]) => [key, value.definition]),
);
