sonar.projectKey=Stockify
sonar.projectName=Stockify
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.8
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=crypto_agent_final.py, sac_backtest.py, main.py
sonar.host.url=http://localhost:9000
sonar.token=sqp_3144e7c08fe77fc4c5093b937c1d93b514902da7
